### ISSUE TITLE
Failed opening required autoload.php

### ISSUE THREAD

**Issue by vitor-ao** [hexonet/whmcs-ispapi-ssl#83]
After installing the latest update (from 9.0.0), i get the following error:
`Whoops\Exception\ErrorException: require_once(): Failed opening required 'K:\PortableApps\Laragon\www\whmcs\modules\servers\ispapissl/vendor/autoload.php' (include_path='.;K:/PortableApps/Laragon/etc/php/pear') in K:\PortableApps\Laragon\www\whmcs\modules\servers\ispapissl\ispapissl.php:12`
(Testing environment is Windows).

https://github.com/hexonet/whmcs-ispapi-ssl/blob/c938783cc4285df89a589623d3d0ddb10ad715f9/servers/ispapissl/ispapissl.php#L12

**Comment by papakai** [comment]
Thanks for reporting @vitor-ao!
