### ISSUE TITLE
whmcs 8 ssl import oops

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-ssl#86]
Oops!
Something went wrong and we couldn't process your request.

TypeError: Return value of HEXONET\WHMCS\ISPAPI\SSL\DBHelper::getProductId() must be of the type int, null returned in .../public_html/members/modules/servers/ispapissl/lib/DBHelper.php:154
Stack trace:
#0 .../public_html/members/modules/servers/ispapissl/lib/SSLHelper.php(164): HEXONET\WHMCS\ISPAPI\SSL\DBHelper::getProductId('COMODO_POSITIVE...')
#1 .../public_html/members/modules/addons/ispapissl_addon/ispapissl_addon.php(84): HEXONET\WHMCS\ISPAPI\SSL\SSLHelper::importProducts()
#2 .../public_html/members/adminadmin/addonmodules.php(0): ispapissl_addon_output(Array)
#3 {main}

**Comment by h9k** [comment]
Please state your WHMCS version

**Comment by HamidRadmani** [comment]
Version: 8.1.3

**Comment by h9k** [comment]
Thanks for reporting this @HamidRadmani - it has been fixed in version 9.2.2.

**Comment by HamidRadmani** [comment]
Thanks for your very fast reaction and fixing it🙏
