### ISSUE TITLE
request to add ssl Provider logo

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-ssl#89]
Hello
if this is possible, The module work perfectly:

automatically add or update Provider logo when import products like this: https://opensrs.com/services/ssl/
automatically add or update product specification like this: https://opensrs.com/services/ssl/digicert-ssl-products/digicert-ssl-plus/

thank you in advance.

**Comment by papakai** [comment]
We will check your feature request in the next ~2 weeks. In general, we are fast with updates, so probably you can expect our response or even an update earlier.

Thanks for forwarding!

**Comment by papakai** [comment]
@HamidRadmani Your follow-up has been received, this is already in work. Sorry for the delay.

**Comment by papakai** [comment]
@HamidRadmani we launched the review with [v9.3.0](https://github.com/hexonet/whmcs-ispapi-ssl/raw/master/whmcs-ispapi-ssl-latest.zip).

HTH

**Comment by HamidRadmani** [comment]
thank you for this great update!
in WHMCS 8.2 , you write the address of the module in this form: <img src="modules/addons/ispapissl_addon/logos/digicert.png" />
but in WHMCS need to read form this address: **store**/modules/addons/ispapissl_addon/logos/digicert.png

then the logos cant display.

**Comment by HamidRadmani** [comment]
thank you for this great update!
in WHMCS 8.2 , you write the address of the module in this form: img src="modules/addons/ispapissl_addon/logos/digicert.png
but in WHMCS need to read form this address: store/modules/addons/ispapissl_addon/logos/digicert.png

then the logos cant display.
