### ISSUE TITLE
Logo cant show due to wrong url

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-ssl#96]
thank you for this great update!
in WHMCS 8.2 , you write the address of the module in this form: img src="modules/addons/ispapissl_addon/logos/digicert.png
but in WHMCS need to read form this address: store/modules/addons/ispapissl_addon/logos/digicert.png

then the logos cant display.

**Comment by papakai** [comment]
Thanks for reporting @HamidRadmani. We will work on this tomorrow. Expect an Update latest next week then.

**Comment by h9k** [comment]
Sorry about that.
The issue should be fixed in version 9.3.1.
Just run the import again with the description switch on, and it should update the product descriptions to contain the correct URLs.
